### ISSUE TITLE
Plus and Minuses for Time Zone Information in Date Time Strings

### ISSUE THREAD

**Issue by IdemenB** [samscott89/serde_qs#66] opened 2022-07-06 13:31 UTC
Hi,

I just noticed, when I use serde_qs within Actix4 to capture the query parameters sent with a HTTP request, the crate disposes of plus and minus signs that must be available in date time with TZ strings. Below are two samples.

`1996-12-19T16:39:57-08:00`

`2022-06-29T07:02:50+00:00`

I expect to get them as `String` instances and parse to DateTime using `DateTime::parse_from_rfc3339()`

**Comment by samscott89** [comment] 2022-07-10 01:45
This appears to be a duplicate of #65

**Closed by samscott89** 2022-07-10 01:45 UTC
